server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/query?serverTimezone=GMT%2b8
    username: root
    password: liubo123

mybatis:
  mapper-locations: classpath:mapper/*.xml
